spring:

  application:
    name: Spring-boot-app
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/keycloak
          jwk-set-uri: http://localhost:8180/realms/keycloak/protocol/openid-connect/certs
          


jwt:
  auth:
    converter:
      resource-id: account
      principal-attribute: preferred_username

server:
      port: 8081
